init
wavefrontHQ/nodejs-metrics-wavefront pull request #20
Opened 2019-09-13 23:39 UTC by djia-vm-wf

2019-09-13 23:44 UTC, akodali18 reviewed
Can we add unit tests for this as well.

2019-09-13 23:58 UTC, aliu-vmware commented on lib/helper.js
> +  var tagsType = typeof tags;
Couple of things here:
1. These checks should be done before tagsArray is executed.
2. typeof and types in general are very tricky in javascript.  You should try to handle as many cases as possible.  Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Examples for the sort of weirdness that can occur.
3. prefer !== over != in javascript
4. avoid throwing non-Errors.  This is easily fixed by switching to `throw new Error("message here")`

2019-09-13 23:59 UTC, aliu-vmware commented on lib/helper.js
>    return metricName + tagSeparator + JSON.stringify(tagsArray) ;
optional: prefer template string construction over string addition.  See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2019-09-14 00:00 UTC, aliu-vmware commented on test/helper.js
> +      registry.addTaggedMetric("request.counter1", c, "{\"key1\":\"val1\"}");
should have multiple cases trying other weird stuff: null, Date, array, etc.

2019-09-14 00:01 UTC, aliu-vmware requested changes
See inline comments.

2019-09-14 00:04 UTC, akodali18 commented on lib/helper.js
> +    throw "Wrong Tags Object Sent To The API"
We can make this exception as clear to the user as possible with info about "why it failed" and "the expected format"

2019-09-16 21:21 UTC, aliu-vmware approved these changes

2019-09-16 21:26 UTC, akodali18 reviewed
The second change - https://github.com/wavefrontHQ/nodejs-metrics-wavefront/pull/20/commits/b7b15c1ea1eb695b1e3467672a928163aa892587 seems to have broken the sdk build. 
Rest LGTM.

2019-09-16 21:39 UTC, akodali18 approved these changes

2019-09-16 21:47 UTC, merged